#!/bin/bash

# all vars set here


M_MANAGMENT_IP=192.168.1.74
M_IP=192.168.56.10
M_HOSTNAME=nismaster

DOMAIN=osh.kg
DEST=/root
NET1=enp0s3
NET2=enp0s8


C_MANAGMENT_IP=192.168.1.79
C_IP=192.168.56.20
C_HOSTNAME=nisclient



